plugins {
	id 'matcher.common'
	id 'matcher.publishing.maven'
	id 'matcher.publishing.github.no-natives'
	id 'matcher.openrewrite.java17'
	id 'org.gradlex.extra-java-module-info'
	id 'application'
}

base {
	archivesName = 'matcher-cli'
}

java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17

	if (!JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_17)) {
		toolchain {
			languageVersion = JavaLanguageVersion.of(17)
		}
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

dependencies {
	api project(':matcher-core')
	api "com.beust:jcommander:${jcommander_version}"
	runtimeOnly "org.tinylog:tinylog-impl:${tinylog_version}"
	runtimeOnly "org.tinylog:slf4j-tinylog:${tinylog_version}"
}

extraJavaModuleInfo {
	// JCommander
	automaticModule("com.beust:jcommander", "jcommander")
}

application {
	mainModule = 'matcher.cli'
	mainClass = 'matcher.cli.Main'
}

jar {
	processResources.exclude('tinylog-dev.properties')
}
